### ISSUE TITLE
Log for RequestBodyInterceptor

### ISSUE THREAD

**Issue by marshalluous** [Viascom/groundwork#37]
Hi
I really like the log. It is a major tool of FoxHttp. It tells me exactly what I send over the network. Although I miss one feature:
- when I created my own RequestBodyInterceptor (RBI) and therewith encrypt the data of my request, the log does show me the data I am sending BEFORE I use the RBI, but it does not show me what I send AFTER the RBI has done its work.

Is there a feature which can do that?
Thanks in advance. =)

**Comment by itsmefox** [comment]
Hi @marshalluous 

The short answer is: **No** there is no such feature. 

This is because the interceptor (RequestBodyInterceptor) gets invoked after the body has been set to the output stream buffer. So the part of setting the body is technically done for FoxHttp.

_We will check if such a feature (logging after one or more interceptors are been invoked) is needed._

**Actual Solution:**
If you like to log the content after your own modification to the output stream. You can use the log function of FoxHttp (get the FoxHttpClient from the context) as last call in your RequestBodyInterceptor. With this solution you can also retrace the changes after each RequestBodyInterceptor if you have more than one:

```java
ByteArrayOutputStream newOutputStream = context.getRequestBody().getOutputStream();
context.getClient().getFoxHttpLogger().log("-> setRequestBodyStream(" + newOutputStream.toString() + ")");
```

**Comment by itsmefox** [comment]
Hi @marshalluous 

Unfortunately, we can not offer this functionality because we want to give our users the greatest possible freedom with Interceptors. In Addition this change would require a change in all other interceptors, which would make logging with a large number of interceptors more difficult.

Cheers, Patrick
